version: "2"

services:
  db:
    image: postgres:11
    container_name: endpoint-db
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./docker/data/postgres:/var/lib/postgresql/data

  web:
    build: .
    image: endpoint/web
    container_name: endpoint-web
    command: bash -c "bundle && bin/rails db:create db:migrate db:seed && bundle exec puma -p 80"
    volumes: &web-volumes
      - ./:/app
      - ~/.bash_history:/root/.bash_history
    ports:
      - "80:80"
    links:
      - db
    environment: &web-environment
      APP_ENV: development
      NODE_ENV: development
      POSTGRESQL_HOST: db
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: 1
